---
- name: Set SELinux to permissive mode.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  register: selinuxdisabled

- name: Reboot for changes to take effect.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: selinuxdisabled is changed

- name: Wait for the reboot to complete.
  wait_for_connection:
    connect_timeout: 30
    sleep: 5
    delay: 5
    timeout: 300
  when: selinuxdisabled is changed
