---
- name: Disable SELinux
  include_tasks: disable_selinux.yaml

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Add EPEL repository
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - epel-release
    - syslog-ng
  when: "'syslog-ng' not in ansible_facts.packages"
